config/routes.rb
Clicknslide::Application.routes.draw do
 

  devise_for :users
  
  resources :users
  
  resources :comments

   resources :pages
 
  resources :books do
    resources :pages
  end
  
  root :to=>"books#index"

end

app/views/pages/_comments.html.erb
 <table style="text-align: left; width: 100%;" border="1" cellpadding="2" cellspacing="2">

  <tbody>
    <tr>
      <td style="vertical-align: top; background-color: rgb(255, 153, 255);"><span style="color: rgb(204, 51, 204); font-family: Helvetica,Arial,sans-serif; font-weight: bold;">Add Comment</span><br>
      </td>
      <td style="vertical-align: top;">
      	<div class="newComment">
      	<%= form_for(@comment,:remote=>true) do |f| %>
Comment:<br>
		<%= f.text_area :comment, :rows => 5, :cols => 50 %>

			<script type="text/javascript">
			  $(function() {
			    $('textarea').tinymce({
			      theme: 'simple'
			    });
			  });
			</script>
		<%= f.hidden_field :page_id, :value=>@page.id %>
		<%= f.submit %>
		<%end%>
		</div>
      <br>
      </td>
    </tr>
     <% @comments.each_with_index do |comment| %>
	<tr>
      <td style="vertical-align: top; background-color: rgb(255, 153, 255);">
      	<big style="font-family: Helvetica,Arial,sans-serif; color: rgb(204, 51, 204);">
      		<%= #comment.user.name
       %></big><br>
      </td>
      <td style="vertical-align: top;"><%= comment.comment.html_safe %><br>
      </td>
    </tr>
     <%end%>
        </div>
  </tbody>
</table>
<div style="text-align: right;"><%= paginate @comments, :remote=>true %></div>

app/views/pages/_form.html.erb
<%= form_for(@page,:html=>{:multipart=>true}) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  	<%= f.label :file, "Picture:"%><br />
  	<%= f.file_field :file %>
  	</div>

  <div class="field">
    <%= f.label :translation %><br />
    <%= f.text_area :translation %>
  </div>
  <div><%= f.hidden_field :book_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Translation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.translation %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>
<div>
	<table style="text-align: left; width: 100%;" border="1" cellpadding="2" cellspacing="2">
		<tr>
			<td width="25%" style="text-align: right;"><%= link_to(mouseoverimage("/images/left.png","/images/left_hover.png"), book_page_path(@page.book_id,@page.previous_page)) if !@page.previous_page.nil? %></td>
			<td style="text-align: center;"><%= image_tag @page.file_url.to_s,:style=>'width: 400px;', :id=>"centerImage" %></td>
			<td width="25%"><%= link_to(mouseoverimage("/images/right.png","/images/right_hover.png"), book_page_path(@page.book_id,@page.next_page)) if !@page.next_page.nil? %></td>
		</tr>
	    <tr>
      		<td style="vertical-align: top; background-color: rgb(255, 153, 255);"><span style="font-family: Helvetica,Arial,sans-serif; font-weight: bold; color: rgb(204, 102, 204);">Translation</span><br></td>
      		<td colspan="2" rowspan="1" style="vertical-align: top;"><span style="font-weight: bold;">
      			<%= @page.translation %>
      		</td>
    </tr>
	</table>
</div>
<br />
    <div id="comments">
    <%= render "comments"%>
    </div>

app/views/pages/show.js.erb
// here we're taking our newly created post and appending it to the list shown above
$('#comments').html("<%= escape_javascript(render :partial=>"comments") %>");